"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { duplicateMap, type MapDoc } from "@/lib/maps";
import { useAuth } from "@/lib/auth";
import { Avatar } from "./Avatar";

/* A map shown as a card in the dashboard grid — thumbnail-ish header + metadata row,
   with a hover kebab menu for actions (duplicate, delete). */
export function MapCard({ map, onRequestDelete }: { map: MapDoc; onRequestDelete: (m: MapDoc) => void }) {
  const { identity } = useAuth();
  const when = map.updatedAt?.toDate?.();
  const ago = when ? relTime(when) : "";
  const [menu, setMenu] = useState(false);
  const [dup, setDup] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  const duplicate = async () => {
    if (!identity) return;
    setDup(true);
    try {
      await duplicateMap(identity, map);
    } catch (e) {
      alert("Couldn’t duplicate: " + (e instanceof Error ? e.message : e));
    } finally {
      setDup(false);
    }
  };

  useEffect(() => {
    const close = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setMenu(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, []);

  return (
    <div className="relative group">
      <Link href={`/map/${map.id}`} className="card overflow-hidden block">
        <div className="h-36 bg-[#fbfbfa] border-b border-[color:var(--color-line)] relative grid place-items-center">
          <div
            className="absolute inset-0"
            style={{
              backgroundImage: "radial-gradient(#e3e5e8 1px, transparent 1px)",
              backgroundSize: "16px 16px",
            }}
          />
          {map.status === "ready" && map.svgUrl ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={map.svgUrl}
              alt=""
              className="relative max-h-28 max-w-[85%] object-contain opacity-90"
            />
          ) : map.status === "ready" && map.thumbSvg ? (
            <div
              className="relative h-28 w-[85%] [&>svg]:h-full [&>svg]:w-full"
              // trusted: generated by our own converter
              dangerouslySetInnerHTML={{ __html: map.thumbSvg }}
            />
          ) : (
            <StatusBadge status={map.status} />
          )}
        </div>
        <div className="p-3">
          <div className="text-sm font-medium truncate mb-1.5 pr-6">{map.title}</div>
          <div className="flex items-center gap-2 text-xs text-[color:var(--color-ink-soft)]">
            <Avatar name={map.ownerName} photo={map.ownerPhoto} size={18} />
            <span className="truncate">{map.ownerName}</span>
            {ago && <span className="ml-auto shrink-0">{ago}</span>}
          </div>
        </div>
      </Link>

      {/* kebab menu — overlaid above the Link so it doesn't navigate */}
      <div className="absolute top-2 right-2 z-10" ref={ref}>
        <button
          aria-label="Map actions"
          onClick={() => setMenu((m) => !m)}
          className="h-8 w-8 grid place-items-center rounded-full bg-[color:var(--color-surface)]/90 border border-[color:var(--color-line)] text-[color:var(--color-ink-soft)] opacity-0 group-hover:opacity-100 data-[open=true]:opacity-100 hover:bg-[#f1f3f4] transition"
          data-open={menu}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
            <circle cx="12" cy="5" r="1.6" />
            <circle cx="12" cy="12" r="1.6" />
            <circle cx="12" cy="19" r="1.6" />
          </svg>
        </button>
        {menu && (
          <div className="absolute right-0 top-9 w-40 card p-1">
            <button
              onClick={() => {
                setMenu(false);
                duplicate();
              }}
              className="w-full text-left text-sm px-3 py-2 rounded-md hover:bg-[#f1f3f4] flex items-center gap-2"
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="9" y="9" width="11" height="11" rx="2" />
                <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
              </svg>
              Duplicate
            </button>
            <button
              onClick={() => {
                setMenu(false);
                onRequestDelete(map);
              }}
              className="w-full text-left text-sm px-3 py-2 rounded-md hover:bg-[#fce8e6] text-[#c5221f] flex items-center gap-2"
            >
              <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="3 6 5 6 21 6" />
                <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
              </svg>
              Delete map
            </button>
          </div>
        )}
      </div>

      {dup && (
        <div className="absolute inset-0 z-20 grid place-items-center rounded-lg bg-[color:var(--color-surface)]/70 text-xs text-[color:var(--color-ink-soft)]">
          <span className="flex items-center gap-2">
            <span className="h-3.5 w-3.5 rounded-full border-2 border-[color:var(--color-line)] border-t-[color:var(--color-accent)] animate-spin" />
            Duplicating…
          </span>
        </div>
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: MapDoc["status"] }) {
  if (status === "processing")
    return (
      <div className="relative flex items-center gap-2 text-xs text-[color:var(--color-ink-soft)]">
        <span className="h-3.5 w-3.5 rounded-full border-2 border-[color:var(--color-line)] border-t-[color:var(--color-accent)] animate-spin" />
        Processing…
      </div>
    );
  if (status === "error")
    return <div className="relative text-xs text-[color:var(--color-ink-soft)]">Conversion failed</div>;
  return <div className="relative text-xs text-[color:var(--color-ink-soft)]">No preview</div>;
}

function relTime(d: Date): string {
  const s = (Date.now() - d.getTime()) / 1000;
  if (s < 60) return "just now";
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`;
  return d.toLocaleDateString();
}
